name: Release
on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:

  deploy:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./..

      - name: Get Tag Version
        run: |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "tag=${{ github.ref_name }}"

      - name: Changelog
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/lack-io/changelog@latest

      - name: Generate Changelog
        run: |
          changelog --last --output ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
